DROP DATABASE IF EXISTS app_user;
CREATE DATABASE app_user;
use app_user;

DROP TABLE IF EXISTS `T_USER`;

CREATE TABLE `T_USER` (
  `T_ID` BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
  `T_NAME` VARCHAR(255) UNICODE NOT NULL COMMENT '用户名',
  `T_NICK_NAME` VARCHAR(255) COMMENT '用户姓名',
  `T_AGE` INT COMMENT '年龄'
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 COMMENT '用户信息表';


DROP TABLE IF EXISTS `T_ADDRESS`;
CREATE TABLE `T_ADDRESS` (
  `T_ID` BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
  `T_ADDRESS_NAME` VARCHAR(255) NOT NULL COMMENT '用户名',
  `T_CITY_NAME` VARCHAR(255) COMMENT '城市名称',
  `T_CITY_CODE` VARCHAR(255) COMMENT '城市代码',
  `T_USER_ID` BIGINT(20) COMMENT '用户ID',
  FOREIGN KEY (`T_USER_ID`) REFERENCES T_USER(T_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 COMMENT '用户信息表';




