DROP DATABASE IF EXISTS app_user;
CREATE DATABASE app_user;
use app_user;

DROP TABLE IF EXISTS `T_USER`;

CREATE TABLE `T_USER` (
  `T_ID` BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
  `T_NAME` VARCHAR(255) UNICODE NOT NULL COMMENT '用户名',
  `T_NICK_NAME` VARCHAR(255) COMMENT '用户姓名',
  `T_AGE` INT COMMENT '年龄'
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 COMMENT '用户信息表';




